### ISSUE TITLE
No info displayed in the packet dissector window of the UI

### ISSUE THREAD

**Issue by doughudson** [cetic/foren6#12]
I built the examples/ipv6/rpl-udp example with the TI CC2538 and was able to see the nodes/connections, and events on the UI.  Same results when running with Sky nodes.  However, I was unable to see anything in the packet dissector window of the UI.  I verified that I am in the wireshark group.  I also tried setting the "Old Tshark" field in the UI's preferences, but that didn't work either.  I also tried running the UI with sudo foren6 but got a warning from TShark about running as root.  Still no packets were displayed.

Are there any other steps that I need to try?

Thanks in advance for any suggestions.

**Comment by leosteinfeld** [comment]
Similar behavior for me. Any news on this?
Thanks.

**Comment by laurentderu** [comment]
The packet window was still using the old tshark parameters, it's now fixed in the latest version.
